project: your-project-id # 各自のプロジェクトIDを指定
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# ルーティング
handlers:
# すべてのリクエストをmain.pyに向ける
- url: .*
  script: main.app # main.pyではない

# 使用ライブラリの指定
libraries:
# Webフレームワークのwebapp2を使用する
- name: webapp2
  version: "2.5.2"